// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9gOSqLgkkWtJRtpq1uuYobksF_O680HA',
    appId: '1:568324793355:android:7bc46609e00a8d7222530e',
    messagingSenderId: '568324793355',
    projectId: 'pathiq-ai',
    storageBucket: 'pathiq-ai.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB56J5LTvKfSTJYpqO1kn7aXCaLselCzf8',
    appId: '1:568324793355:web:b6fa324121b7ec8b22530e',
    messagingSenderId: '568324793355',
    projectId: 'pathiq-ai',
    authDomain: 'pathiq-ai.firebaseapp.com',
    storageBucket: 'pathiq-ai.firebasestorage.app',
    measurementId: 'G-TNWD1E9R0B',
  );
}
